version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_SIMPLE_REST_URL=http://backend:7777/api/v1
      - VITE_WSS_ENDPOINT=wss://spiritnet.kilt.io
    networks:
      - attester

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: dena
      POSTGRES_PASSWORD: secrect
      POSTGRES_DB: attester
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - attester

  backend:
    build:
      context: ./backend
    ports:
      - "7777:7777"
    environment:
      - ATTESTER_DID_SEED="analyst bomb away undo globe believe quiz aisle shrug mail parade emerge"
      - ATTESTER_ATTESTATION_SEED="analyst bomb away undo globe believe quiz aisle shrug mail parade emerge"
      - PAYER_SEED="vibrant supreme service cat pig middle crazy notice prison head flip eye"
      - HOST_NAME="0.0.0.0"
      - WSS_ADDRESS="wss://peregrine.kilt.io:443/parachain-public-ws"
      - DATABASE_URL="postgres://dena:secrect@database:5432/attester"
      - RUST_LOG="trace cargo run"
    networks:
      - attester

networks:
  attester:
volumes:
  database_volume:
