version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: attester
      POSTGRES_USER: dena
      POSTGRES_PASSWORD: secrect
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - default

  server:
    build: ./
    environment:
      RUNTIME: peregrine
      CONFIG: /app/config.yaml
    ports:
      - "5656:5656"
    depends_on:
      - postgres
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - default

networks:
  default:

volumes:
  data: