on:
  workflow_dispatch:
    types: [created]
  push:
    branches:
      - main
      - test

name: Dev deployment

jobs:
  deploy:
    name: Build image and push to Amazon ECR
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
      - name: test env variables
        run: |
          echo "$BACKEND_URL $AUTH_URL"
        env:
          BACKEND_URL: ${{ vars.BACKEND_URL }}
          AUTH_URL: ${{ vars.AUTH_URL }}

        with:
          args: rollout restart deployment dena-attester -n dena-attester-dev
